# Generated by Django 4.0 on 2022-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_marketing_list_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatars/"),
        ),
    ]
